# Generated by Django 2.2.5 on 2021-01-31 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiasHorarios',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=50, verbose_name='Data')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('hora_fim', models.TimeField(verbose_name='Hora fim')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('cod_disc', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('cod_sala', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(verbose_name='Número da sala')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('cod_turma', models.AutoField(primary_key=True, serialize=False)),
                ('identificacao', models.CharField(max_length=255, verbose_name='Identificação da turma')),
            ],
        ),
        migrations.CreateModel(
            name='TurmaSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_horario_ah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DiasHorarios')),
                ('disciplina_ah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Salas')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Turma')),
            ],
        ),
    ]
